disabled_rules: # rule identifiers to exclude from running
  - file_length
  - function_body_length
  - line_length
  - cyclomatic_complexity
  - todo
  - legacy_constructor
variable_name:
  excluded:
    - id
    - fd
